export const GET_CONTENT_LIST = "GET_CONTENT_LIST";
export const GET_CONTENT_FILTER_PAID = "GET_CONTENT_FILTER_PAID";
export const GET_CONTENT_FILTER_FREE = "GET_CONTENT_FILTER_FREE";
export const GET_CONTENT_FILTER_VIEW = "GET_CONTENT_FILTER_VIEW";
export const GET_CONTENT_FILTER = "GET_CONTENT_FILTER";
